Avast Updates
TechTeamer/avastscan pull request #2
Opened 2021-06-03 09:14 UTC by nikolovjd

2021-06-03 13:24 UTC, tgabi333 requested changes

2021-06-03 13:24 UTC, tgabi333 commented on src/Avast.js
> +    return { history: this.history, is_safe, ...scanResult }
másoljuk a tömböt plz

2021-06-03 13:38 UTC, nikolovjd commented on src/Avast.js
> +    return { history: this.history, is_safe, ...scanResult }
Done

2021-06-03 15:16 UTC, tunderdomb requested changes

2021-06-03 15:16 UTC, tunderdomb commented on src/Avast.js
> +            } {
syntax error

2021-06-03 15:16 UTC, tunderdomb commented on src/Avast.js
> +              this.resultMap.get(rootFileName).is_password_protected = true
a Map.get hívásokat emeld ki légyszi, hogy ne ismétlődjenek feleslegesen

2021-06-03 15:16 UTC, tunderdomb commented on src/Avast.js
> +            if (line.includes('Archive\\ is\\ password\\ protected')) {
Itt miért van kétszer escape-elve a backslash?

2021-06-03 15:16 UTC, tunderdomb commented on src/Avast.js
> +    return { history: [...this.history], is_safe, ...scanResult }
ezt tördeld sorokba légyszi

2021-06-03 16:52 UTC, nikolovjd commented on src/Avast.js
> +    const is_safe = !scanResult.is_infected && !scanResult.is_password_protected && !scanResult.permission_denied
clamav APIjához hasonló, ami snake_case-t használ

2021-06-03 16:59 UTC, nikolovjd commented on src/Avast.js
> +              this.resultMap.get(rootFileName).is_password_protected = true
Done

2021-06-03 16:59 UTC, nikolovjd commented on src/Avast.js
> +    return { history: [...this.history], is_safe, ...scanResult }
Done

2021-06-03 16:59 UTC, nikolovjd commented on src/Avast.js
> +            } {
Fixed

2021-06-03 17:00 UTC, nikolovjd commented on src/Avast.js
> +      // Engine Error
Done

2021-06-03 17:01 UTC, nikolovjd commented on src/Avast.js
> +            if (line.includes('Archive\\ is\\ password\\ protected')) {
Így irja ki az avast

2021-06-04 12:23 UTC, tgabi333 approved these changes

2021-06-07 12:09 UTC, merged